name: Lim'Elle Docker

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install --ignore-scripts --no-audit --no-fund
      - name: Build application
        run: npm run build
      - name: Build API image
        run: docker build --pull -t limelle-api:test .
      - name: Inspect image
        run: docker image inspect limelle-api:test
